version: "2"

run:
  timeout: 20m
  issues-exit-code: 1
  tests: false

output:
  formats:
    tab:
      print-linter-name: true

linters:
  default: none
  enable:
    - govet
    - errcheck
#   - copyloopvar
    - gocritic
    - revive
    - gosimple
    - lll
    - stylecheck
    - unconvert
    - unparam
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - goconst
    - gosec
    - misspell
    - nakedret
    - prealloc
  exclusions:
    paths:
      - cicd
      - docs
      - test
      - third-party
    rules:
      - linters:
          - gosec
        text: "G[105,202,401,505]"
      - linters:
          - goimports
        text: "File is not `goimports`-ed"
      - linters:
          - govet
        text: "shadows declaration"
      - linters:
          - staticcheck
        text: "SA1019:"
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocyclo:
      min-complexity: 10
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    lll:
      line-length: 120
      tab-width: 1
    unparam:
      check-exported: false
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    gosec:
      includes:
        - G401
        - G402
        - G404

formatters:
  enable:
    - gofumpt
    - goimports
